@startuml DiagramaMario
class Personaje
class CatMario
class Vida
class Puntuacion
class Nivel
class Trampa
class Plataforma
class Block
class BlockInvisible
class BlockPunzante
class Suelo
class Tubo
class TuboTrampa
class Enemigo
class Cebolla
class CebollaPelo
class Robot
class Rayo
class NubeTrap
class BlockCat
class Abismo
class Checkpoint
class PowerUp
class HongoRojo
class HongoMorado 
class Estrella
class Moneda
class CatVolador
class BlockInvisibleHongomorado
class Bandera

CatMario                   --|> Personaje
BlockInvisible             --|> Block
BlockPunzante              --|> Block
BlockCat                   --|> Block
BlockInvisibleHongomorado  --|> Block
Block                      --|> Plataforma
Suelo                      --|> Plataforma
Tubo                       --|> Plataforma
TuboTrampa                 --|> Tubo
Trampa                     --|> Obstaculo
BlockCat                   --|> Trampa
BlockInvisibleHongomorado  --|> Trampa
Abismo                     --|> Trampa
NubeTrap                   --|> Trampa
BlockPunzante              --|> Trampa
HongoRojo                  --|> Trampa  
HongoMorado                --|> Trampa        
Estrella --|> Trampa
TuboTrampa --|> Trampa
CatVolador --|> Trampa
Cebolla --|> Enemigo
CebollaPelo --|> Enemigo
Robot --|> Enemigo
CatVolador --|> Enemigo
Nubetrap --|> Enemigo
Rayo --|> Proyectil
CatVolador --|> Proyectil
HongoRojo --|> PowerUp
HongoMorado --|> PowerUp
Estrella --|> PowerUp
Moneda --|> PowerUp

CatMario     *-- Vida
CatMario     *-- Puntuacion
Nivel        *-- Plataforma
Nivel        *-- Enemigo
Nivel        *-- Trampa
Nivel        *-- Checkpoint
Nivel        *-- Bandera

Personaje         0-- Trampa  
Robot             0-- block
CatMario          0-- PowerUp
CatMario          0-- Moneda
CatMario          0-- HongoRojo
CatMario          0-- Checkpoint
CatMario          0-- Trampa
Robot             0-- Enemigo 
TuboTrampa        0-- Enemigo
BloqueInvisible   0-- Trampa
CatMario          0-- Bandera
@enduml