@startuml DiagramaMario
class Usuario{ 
-Personaje personaje
-Control control
+jugar()
+Caminar(control)
}
class Personaje{
-CatMario catMario   
-Movimiento movimiento
+Caminar()
}
class Item{
+Vida:tomar(PowerUp)
}
class CatMario{
-Vida vidas[]
-PowerUp powerup []
+Caminar()
+Usar(Trampa)
+Marcador:Recoger(Item)
+Impactar(BlockPunzante)
+Marcador:morir(Enemigo)
+Marcador:morir(Trampa)
+Marcador:morir(Abismo)

}
class Marcador{
-Vida vida
-Puntaje puntaje
+
}
class Movimiento
class Control
class Vida
class Nivel{
-Plataforma plataformas[]
-Enemigo enemigos[]
-Trampa trampas[]
-Checkpoint checkpoint


}
class Trampa
class Plataforma
class Block
class BlockInvisible
class BlockPunzante
class Suelo
class Tubo
class TuboTrampa{
-CatTubo catTubo [1]
-CatVolador catVolador[1]
+Entrar ()

}
class Enemigo
class Cebolla
class CebollaPelo
class Robot
class Rayo
class NubeTrap
class BlockCat
class Abismo
class Checkpoint
class PowerUp
class HongoRojo
class HongoMorado 
class Estrella
class Moneda
class CatVolador
class BlockInvisibleHongomorado
class Bandera
class CatTubo

class Proyectil

CatMario                   --|> Personaje

BlockInvisible             --|> Block
BlockPunzante              --|> Block
BlockCat                   --|> Block
BlockInvisibleHongomorado  --|> Block

Block                      --|> Plataforma
Suelo                      --|> Plataforma
Tubo                       --|> Plataforma
TuboTrampa                 --|> Tubo

Trampa                     --|> Obstaculo
BlockCat                   --|> Trampa
BlockInvisibleHongomorado  --|> Trampa
BlockInvisible             --|> Trampa
Abismo                     --|> Trampa
NubeTrap                   --|> Trampa
BlockPunzante              --|> Trampa
HongoRojo                  --|> Trampa  
HongoMorado                --|> Trampa        
Estrella                   --|> Trampa
TuboTrampa                 --|> Trampa
CatVolador                 --|> Trampa

Cebolla                    --|> Enemigo
CebollaPelo                --|> Enemigo
Robot                      --|> Enemigo
CatVolador                 --|> Enemigo
Nubetrap                   --|> Enemigo
CatTubo                    --|> Enemigo

Rayo                       --|> Proyectil
CatVolador                 --|> Proyectil
Item                       --|> PowerUp
HongoRojo                  --|> PowerUp
HongoMorado                --|> PowerUp
Estrella                   --|> PowerUp
Moneda                     --|> PowerUp

Usuario                   "1"   *-- "1"  Personaje
Personaje                 "1"   *-- "n"  Marcador
Enemigo                   "1"   *-- "1"  Vida
CatMario                  "1"   *-- "*"  Vida
Nivel                     "1"   *-- "*"  Plataforma
Nivel                     "1"   *-- "20" Enemigo
Nivel                     "1"   *-- "30" Trampa
Nivel                     "1"   *-- "1"  Checkpoint
Nivel                     "1"   *-- "1"  Bandera 
Nivel                     "1"   *-- "n"  Obstaculo
Nivel                     "1"   *-- "1"  CatMario

Control                   "1"   o-- "1" CatMario
Usuario                   "1"   o-- "1" CatMario
Usuario                   "1"   o-- "1" Control
BlockInvisibleHongomorado "1"   o-- "*" HongoMorado 
CatTubo                   "1"   o-- "1" Tubo 
Personaje                 "1"   o-- "n" Trampa
Robot                     "1"   o-- "1" Block
CatMario                  "1"   o-- "0" Item
CatMario                  "1"   o-- "1" Checkpoint
CatMario                  "1"   o-- "1" Trampa
CatMario                  "1"   o-- "1" Bandera
@enduml